apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  progressDeadlineSeconds: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ccgc5368.azurecr.io/react:v1
        imagePullPolicy: Always            
        ports:
        - name: frontend
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "500Mi"
            cpu: "200m"
