apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ccgc5368frontend
  name: frontend-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: frontend
