# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'fb54eef2-87cf-4d64-9120-b5596e90e074'
  imageRepository: 'test01'
  containerRegistry: 'ccgc5368.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/db/build/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |      
          echo 'Hello world'