apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  progressDeadlineSeconds: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: ccgc5368.azurecr.io/python:v2
        imagePullPolicy: Always            
        ports:
        - name: backend
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 0
          privileged: true
        livenessProbe:
          httpGet:
           path: /cars
           port: backend
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
           path: /cars
           port: backend
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1

