apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ccgc5368backend
  name: backend-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: backend
