apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8000
    nodePort: 30146
    name: backend
  selector:
    app: backend
